Repository ZupIT/docs-ritchie, pull requests merged in 2021-07, with the labels that each got.

#114 Documentation in pt/br and en for mapping docker volumes.
  content/en/Formulas/Configure Inputs.md
  content/pt-br/Fórmulas/Arquivo Config.md
Labels: tech writer review

#115 docs: add workspace flag in rename formula command
  content/en/Formulas/Rename formulas.md
  content/en/Standard Inputs/Core Commands.md
  content/pt-br/Fórmulas/Renomear Fórmulas.md
  content/pt-br/Standard Inputs/Comandos Core.md
Labels: tech writer review

#116 Update auto assign reviewers and author to PR
  .github/auto_assign.yml
  .github/workflows/add-reviewers.yml
  .github/workflows/auto-assign.yml
Labels: ready for review

#120 add correct youtube video to overview section
  .github/auto_assign.yml
  content/en/Overview.md
  content/pt-br/Visão geral.md
Labels: overview-section
