Repository ZupIT/docs-ritchie, pull requests merged in 2021-06, with the labels that each got.

#88 Add Workspaces section
  content/en/Formulas/Delete formulas.md
  content/en/Formulas/Group formulas.md
  content/en/Formulas/Publish formulas.md
  content/en/Formulas/Rename formulas.md
  content/en/Formulas/Share formulas.md
  content/en/Formulas/Workspaces.md
  content/en/Reference/repo and workspaces.md
  content/pt-br/Fórmulas/Apagar fórmulas.md
  content/pt-br/Fórmulas/Compartilhar fórmulas.md
  content/pt-br/Fórmulas/Encapsular fórmulas.md
  content/pt-br/Fórmulas/Publicar fórmulas.md
  content/pt-br/Fórmulas/Renomear Fórmulas.md
  content/pt-br/Fórmulas/Workspaces.md
  content/pt-br/Referência/repo and workspace.md
  static/shared/rit-add-workspace.gif
  static/shared/rit-delete-workspace.gif
  static/shared/rit-list-workspace.gif
  static/shared/rit-update-workspace.gif
Labels: ready for review, tutorials-section

#82 Add `rit update workspace` command
  content/en/Reference/List of commands and flags.md
  content/en/Standard Inputs/Core Commands.md
  content/pt-br/Referência/Lista de comandos e flags.md
  content/pt-br/Standard Inputs/Comandos Core.md
Labels: ready for review, tech writer review

#93 add installers linux and winget (EN + PT)
  content/en/Getting Started/Linux.md
  content/en/Getting Started/Windows.md
  content/pt-br/Primeiros Passos/Linux.md
  content/pt-br/Primeiros Passos/Windows.md
Labels: getting-started-section, tech writer review

#98 doc: flags of rit init and rit update repo
  content/en/Standard Inputs/Core Commands.md
  content/pt-br/Standard Inputs/Comandos Core.md
Labels: tech writer review

#106 env: remove build-dev pipeline
  .github/workflows/build-dev.yml
Labels: ready for review

#103 create formula flags
  content/en/Standard Inputs/Core Commands.md
  content/pt-br/Standard Inputs/Comandos Core.md
Labels: flags-section

#104 Add reviewers workflow
  .github/workflows/add-reviewers.yml
Labels: enhancement

#108 docs: flag delete formula
  content/en/Standard Inputs/Core Commands.md
  content/pt-br/Standard Inputs/Comandos Core.md
Labels: flags-section, ready for review, tech writer review

#109 Input flags enhancement
  content/en/Formulas/Hello World Formula.md
  content/en/Formulas/Rename formulas.md
  content/en/Standard Inputs/Core Commands.md
  content/en/Standard Inputs/Formulas commands.md
  content/en/Standard Inputs/Input flag.md
  content/pt-br/Fórmulas/Executar uma fórmula Hello World.md
  content/pt-br/Fórmulas/Renomear Fórmulas.md
  content/pt-br/Standard Inputs/Comandos Core.md
  content/pt-br/Standard Inputs/Comandos de fórmulas.md
  content/pt-br/Standard Inputs/visao geral.md
Labels: flags-section, ready for review, tech writer review

#112 add installation command for sudo-free environments
  content/en/Getting Started/Linux.md
  content/en/Getting Started/Macos.md
  content/pt-br/Primeiros Passos/Linux.md
  content/pt-br/Primeiros Passos/Macos.md
Labels: getting-started-section
